name: Tests
on: [push]
jobs:
  kind-tests:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.20
      - name: Install latest version of Kind
        run: |
          GO111MODULE=on go get sigs.k8s.io/kind
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config ./cluster/kind.yaml --wait 30s
      - name: Run tests
        run: |
          go test ./... -v
